(display "type 'exit to exit")
(define (foldr func init l)
  (if (null? l)
      init
      (func (car l) (foldr func init (cdr l)))))
(let loop ()
  (let ((x (readline)))
    (if (eq? x 'exit)
        (display "good bye!")
        (loop))))
